import type { Order } from '@/types'

export const MOCK_ORDERS: Order[] = [
  {
    id: 'demo-1',
    orderNumber: 'STR-2026-0001',
    status: 'IN_PRODUCTION',
    garmentType: 'Jersey',
    quantity: 250,
    fabricType: 'Polyester Mesh',
    fabricWeight: '180 GSM',
    colorCodes: 'Pantone 2728 C, White',
    logoPlacement: 'Center chest, left sleeve',
    decorationMethod: 'Sublimation',
    labelRequirements: 'Woven main label, printed care label',
    shippingAddress: '123 Sports Ave\nLondon, UK EC1A 1BB',
    shippingMethod: 'DHL Express',
    specialNotes: 'Please match exact Pantone colors. Need sample before full production run.',
    timelineRequest: 'Need by April 15, 2026',
    customerId: 'user-1',
    customer: { name: 'James Wilson', email: 'james@sportsteam.com', company: 'Elite Sports FC' },
    assignedToId: null,
    files: [
      { id: 'f1', filename: 'jersey-techpack.pdf', url: '#', type: 'TECH_PACK', orderId: 'demo-1', uploadedBy: 'user-1', createdAt: '2026-03-01T10:00:00Z' },
      { id: 'f2', filename: 'logo-vector.ai', url: '#', type: 'REFERENCE_IMAGE', orderId: 'demo-1', uploadedBy: 'user-1', createdAt: '2026-03-01T10:05:00Z' },
    ],
    messages: [
      { id: 'm1', content: 'Order received! We\'ll send a quote within 24 hours.', orderId: 'demo-1', authorId: 'admin-1', author: { name: 'Strage Team', role: 'ADMIN' }, internal: false, createdAt: '2026-03-01T12:00:00Z' },
      { id: 'm2', content: 'Quote sent — $12.50/unit. Total: $3,125', orderId: 'demo-1', authorId: 'admin-1', author: { name: 'Strage Team', role: 'ADMIN' }, internal: false, createdAt: '2026-03-02T09:00:00Z' },
      { id: 'm3', content: 'Approved! Sending deposit now.', orderId: 'demo-1', authorId: 'user-1', author: { name: 'James Wilson', role: 'CUSTOMER' }, internal: false, createdAt: '2026-03-02T14:00:00Z' },
      { id: 'm4', content: 'Customer paid promptly — priority this order', orderId: 'demo-1', authorId: 'admin-1', author: { name: 'Ali (Production)', role: 'ADMIN' }, internal: true, createdAt: '2026-03-02T15:00:00Z' },
    ],
    createdAt: '2026-03-01T08:30:00Z',
    updatedAt: '2026-03-10T16:00:00Z',
  },
  {
    id: 'demo-2',
    orderNumber: 'STR-2026-0002',
    status: 'QUOTE_SENT',
    garmentType: 'Tracksuit',
    quantity: 100,
    fabricType: 'Cotton Blend',
    fabricWeight: '280 GSM',
    colorCodes: 'Navy #1B2A4A, Gold #D4A843',
    logoPlacement: 'Left chest, back center',
    decorationMethod: 'Embroidery',
    labelRequirements: 'Custom woven neck label',
    shippingAddress: '456 Academy Rd\nDubai, UAE',
    shippingMethod: 'FedEx International',
    specialNotes: null,
    timelineRequest: 'May 2026',
    customerId: 'user-2',
    customer: { name: 'Sarah Ahmed', email: 'sarah@dubaiacademy.ae', company: 'Dubai Sports Academy' },
    assignedToId: null,
    files: [],
    messages: [
      { id: 'm5', content: 'We\'ve sent a detailed quote to your email. Please review.', orderId: 'demo-2', authorId: 'admin-1', author: { name: 'Strage Team', role: 'ADMIN' }, internal: false, createdAt: '2026-03-10T11:00:00Z' },
    ],
    createdAt: '2026-03-09T14:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
  },
  {
    id: 'demo-3',
    orderNumber: 'STR-2026-0003',
    status: 'DELIVERED',
    garmentType: 'Hoodie',
    quantity: 50,
    fabricType: 'French Terry',
    fabricWeight: '320 GSM',
    colorCodes: 'Black #000000',
    logoPlacement: 'Center chest',
    decorationMethod: 'Screen Print',
    labelRequirements: 'Standard',
    shippingAddress: '789 Gym St\nBerlin, Germany',
    shippingMethod: 'DHL Express',
    specialNotes: 'Oversized fit preferred',
    timelineRequest: null,
    customerId: 'user-3',
    customer: { name: 'Max Richter', email: 'max@fitnessbrand.de', company: 'Iron Republic' },
    assignedToId: null,
    files: [
      { id: 'f3', filename: 'hoodie-mockup.png', url: '#', type: 'MOCKUP', orderId: 'demo-3', uploadedBy: 'admin-1', createdAt: '2026-02-15T10:00:00Z' },
    ],
    messages: [],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'demo-4',
    orderNumber: 'STR-2026-0004',
    status: 'ORDER_RECEIVED',
    garmentType: 'Polo Shirt',
    quantity: 500,
    fabricType: 'Pique Cotton',
    fabricWeight: '220 GSM',
    colorCodes: 'White, Navy trim',
    logoPlacement: 'Left chest embroidery',
    decorationMethod: 'Embroidery',
    labelRequirements: 'Custom branded labels',
    shippingAddress: '321 Corporate Blvd\nNew York, NY 10001',
    shippingMethod: 'Sea Freight',
    specialNotes: 'Need size range S-3XL. Custom collar design attached.',
    timelineRequest: 'June 2026',
    customerId: 'user-4',
    customer: { name: 'David Chen', email: 'david@corpwear.com', company: 'Corporate Wear Inc' },
    assignedToId: null,
    files: [
      { id: 'f4', filename: 'collar-design.pdf', url: '#', type: 'TECH_PACK', orderId: 'demo-4', uploadedBy: 'user-4', createdAt: '2026-03-11T08:00:00Z' },
    ],
    messages: [],
    createdAt: '2026-03-11T07:30:00Z',
    updatedAt: '2026-03-11T07:30:00Z',
  },
  {
    id: 'demo-5',
    orderNumber: 'STR-2026-0005',
    status: 'QUALITY_CHECK',
    garmentType: 'Jacket',
    quantity: 75,
    fabricType: 'Softshell',
    fabricWeight: '300 GSM',
    colorCodes: 'Charcoal #333333, Lime #84CC16',
    logoPlacement: 'Left chest, back yoke',
    decorationMethod: 'Heat Transfer',
    labelRequirements: 'Reflective safety labels',
    shippingAddress: '555 Runner Lane\nToronto, ON M5V 2T6',
    shippingMethod: 'FedEx International',
    specialNotes: 'Waterproof zippers required. DWR coating on shell.',
    timelineRequest: 'ASAP',
    customerId: 'user-5',
    customer: { name: 'Lisa Park', email: 'lisa@runclub.ca', company: 'Northern Run Club' },
    assignedToId: null,
    files: [],
    messages: [
      { id: 'm6', content: 'QC photos uploaded — please review before we ship.', orderId: 'demo-5', authorId: 'admin-1', author: { name: 'Strage QC', role: 'ADMIN' }, internal: false, createdAt: '2026-03-11T16:00:00Z' },
    ],
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-03-11T16:00:00Z',
  },
]
